# .appveyor.yml

# Build version
version: '0.9.6.{build}'

# Use the latest available toolchain
image: Visual Studio 2019

# fetch repository as zip archive
shallow_clone: true

# PRs do not increment the build number
pull_requests:
  do_not_increment_build_number: true

# Build configurations
configuration:
  - RelWithDebInfo
  - Release

# Default environment variables
environment:
  IS_BUILD_CANARY: false

# Reset build number to 0 if build is triggered via tag
init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true" -and $env:APPVEYOR_REPO_TAG_NAME) {
        $apiUrl = 'https://ci.appveyor.com/api'
        $headers = @{
            "Authorization" = "Bearer $env:APPVEYOR_TOKEN"
            "Content-type" = "application/json"
        }
        Invoke-RestMethod -Method Put "$apiUrl/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/settings/build-number" -Body '{"nextBuildNumber": 0 }' -Headers $headers
      } else {
        $env:APPVEYOR_REPO_TAG_NAME = "canary"
        $env:IS_BUILD_CANARY = "true"
      }

# Prepare Cpp environment
before_build:
  - cmd: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"

for:
  -
    matrix:
      only:
        - configuration: RelWithDebInfo
    build_script:
      - cmd: |
          md .dist\build\x86-RelWithDebInfo
          cd .dist/build/x86-RelWithDebInfo
          cmake -G "Visual Studio 16 2019" -A Win32 -D_DLL_VERSION="%appveyor_build_version%" -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_BINARY_DIR=".dist/build/x86-RelWithDebInfo" --config RelWithDebInfo ../../..
          cmake --build . --config RelWithDebInfo
  -
    matrix:
      only:
        - configuration: Release
    build_script:
      - cmd: |
          md .dist\build\x86-Release
          cd .dist/build/x86-Release
          cmake -G "Visual Studio 16 2019" -A Win32 -D_DLL_VERSION="%appveyor_build_version%" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_BINARY_DIR=".dist/build/x86-Release" --config Release ../../..
          cmake --build . --config Release

# Do not run unit tests
test: off

# Package artifacts
artifacts:
  - path: .dist\build\x86-RelWithDebInfo\bin
    name: FF7OpenGL-v${appveyor_build_version}_debug
    type: zip
  - path: .dist\build\x86-Release\bin
    name: FF7OpenGL-v${appveyor_build_version}
    type: zip

# Create a GitHub release for every tag
deploy:
  # Deploy only when new tags are pushed
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: FF7OpenGL-v${appveyor_build_version}
    artifact: FF7OpenGL-v${appveyor_build_version}_debug,FF7OpenGL-v${appveyor_build_version}
    pre-release: false
    auth_token:
      secure: SXUyBqg8+wl9fn3xHV2Br0xDH65EyPAnFwJbwcg94wIesv9osQEefC3zxu9iDTUh
    on:
      APPVEYOR_REPO_TAG: true
  # Deploy on each commit
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: FF7OpenGL-v${appveyor_build_version}
    artifact: FF7OpenGL-v${appveyor_build_version}_debug,FF7OpenGL-v${appveyor_build_version}
    pre-release: true
    force_update: true
    auth_token:
      secure: SXUyBqg8+wl9fn3xHV2Br0xDH65EyPAnFwJbwcg94wIesv9osQEefC3zxu9iDTUh
    on:
      IS_BUILD_CANARY: true
