# .appveyor.yml

# Build version
version: '0.9.0.{build}'

# Use the latest available toolchain
image: Visual Studio 2019

# fetch repository as zip archive
shallow_clone: true

# PRs do not increment the build number
pull_requests:
  do_not_increment_build_number: true

# Build configurations
configuration:
  - Debug
  - Release

# Prepare Cpp environment
before_build:
  - cmd: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"

for:
  -
    matrix:
      only:
        - configuration: Debug
    build_script:
      - cmd: |
          md .dist\build\x86-Debug
          cd .dist/build/x86-Debug
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_BINARY_DIR=".dist/build/x86-Debug" ../../..
          cmake --build .
  -
    matrix:
      only:
        - configuration: Release
    build_script:
      - cmd: |
          md .dist\build\x86-Release
          cd .dist/build/x86-Release
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_BINARY_DIR=".dist/build/x86-Release" ../../..
          cmake --build .

# Do not run unit tests
test: off

# Package artifacts
artifacts:
  - path: .dist\build\x86-Debug\bin
    name: FF7OpenGL-v${appveyor_build_version}_debug
    type: zip
  - path: .dist\build\x86-Release\bin
    name: FF7OpenGL-v${appveyor_build_version}
    type: zip

# Create a GitHub release for every tag
deploy:
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: FF7OpenGL-v${appveyor_build_version}
    artifact: FF7OpenGL-v${appveyor_build_version}_debug,FF7OpenGL-v${appveyor_build_version}
    auth_token:
      secure: nr/+SOy4DVnJMVPUs3RZoxoekPAvpW+xxa9sMLNNujPyivbFFva4cEVShrhLgcvq
    on:
      appveyor_repo_tag: true
